	&lt;head&gt;
		&lt;title&gt;&lt;?php echo TITLE; ?&gt;&lt;/title&gt;
		&lt;!-- meta --&gt;
		&lt;meta charset=&quot;UTF-8&quot;&gt;
		&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no&quot; /&gt;
		&lt;!-- icon --&gt;
		&lt;link rel=&quot;shortcut icon&quot; href=&quot;&lt;?php echo HTTP;?&gt;assets/img/icon/amatem_icon_1.ico&quot; type=&quot;image/vnd.microsoft.icon&quot;&gt;
		&lt;link rel=&quot;apple-touch-icon&quot; href=&quot;&lt;?php echo HTTP;?&gt;assets/img/icon/apple_touch_icon_1.png&quot; /&gt;
		&lt;link rel=&quot;apple-touch-icon-precomposed&quot; href=&quot;&lt;?php echo HTTP;?&gt;assets/img/icon/apple_touch_icon_1.png&quot; /&gt;
		&lt;!-- css --&gt;
		&lt;link rel=&quot;stylesheet&quot; href=&quot;&lt;?php echo HTTP;?&gt;assets/css/core.css&quot; type=&quot;text/css&quot;&gt;
		&lt;link rel=&quot;stylesheet&quot; href=&quot;&lt;?php echo HTTP;?&gt;assets/css/common/common.css&quot; type=&quot;text/css&quot;&gt;
		&lt;?php  require_once(PATH.&#039;view/basic/google_analytics.php&#039;); /* google_analytics読み込み*/ ?&gt;
	&lt;/head&gt;
